CREATE TABLE ACCELEROMETER_CHANGE
		(ID INTEGER PRIMARY KEY AUTOINCREMENT,
		LOGTIME TIMESTAMP NOT NULL,
		SERIALNUMBER INT NOT NULL,
		IDX INT,
		ACCELERATION REAL);
CREATE TABLE INTERFACEKIT_INPUTCHANGE
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	LOGTIME TIMESTAMP NOT NULL,
	SERIALNUMBER INT NOT NULL,
	IDX INT,
	STATE INT);
CREATE TABLE INTERFACEKIT_OUTPUTCHANGE
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	LOGTIME TIMESTAMP NOT NULL,
	SERIALNUMBER INT NOT NULL,
	IDX INT,
	STATE INT);
CREATE TABLE INTERFACEKIT_SENSORCHANGE
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	LOGTIME TIMESTAMP NOT NULL,
	SERIALNUMBER INT NOT NULL,
	IDX INT,
	VALUE INT);
CREATE TABLE PHIDGET_ATTACHED
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	LOGTIME TIMESTAMP NOT NULL,
	SERIALNUMBER INT NOT NULL);
CREATE TABLE PHIDGET_DETACHED
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	LOGTIME TIMESTAMP NOT NULL,
	SERIALNUMBER INT NOT NULL);
CREATE TABLE PHIDGET_ERROR
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	LOGTIME TIMESTAMP NOT NULL,
	SERIALNUMBER INT NOT NULL,
	CODE INT NOT NULL,
	DESCRIPTION CHAR(512) NOT NULL);
CREATE TABLE SPATIAL_DATACHANGE
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	LOGTIME TIMESTAMP NOT NULL,
	SERIALNUMBER INT NOT NULL,
	IDX INT,
	ACCELERATION_X REAL,
	ACCELERATION_Y REAL,
	ACCELERATION_Z REAL,
	ANGULARRATE_X REAL,
	ANGULARRATE_Y REAL,
	ANGULARRATE_Z REAL,
	MAGNETICFIELD_X REAL,
	MAGNETICFIELD_Y REAL,
	MAGNETICFIELD_Z REAL);
CREATE TABLE TEMPERATURE_CHANGE
		(ID INTEGER PRIMARY KEY AUTOINCREMENT,
		LOGTIME TIMESTAMP NOT NULL,
		SERIALNUMBER INT NOT NULL,
		IDX INT,
		TEMPERATURE REAL,
		POTENTIAL REAL);
